# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 14:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fpraktikum', '0003_auto_20170730_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses',
                                    to='fpraktikum.FpRegistration', verbose_name='semester half'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester_half',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], null=True, verbose_name='semester half'),
        ),
    ]
