# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 08:12


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fpraktikum', '0005_auto_20170802_0804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fpcoursesecondhalf',
            options={'verbose_name': 'course for second semesterhalf',
                     'verbose_name_plural': 'courses for second semesterhalf'},
        ),
        migrations.AlterField(
            model_name='fpuserregistration',
            name='user_name',
            field=models.CharField(max_length=100, null=True, verbose_name='user name'),
        ),
        migrations.AlterField(
            model_name='fpwaitlist',
            name='user_name',
            field=models.CharField(max_length=100, null=True, verbose_name='user name'),
        ),
    ]
