# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpraktikum', '0006_auto_20170802_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpuserregistration',
            name='partner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrant_user', to='fpraktikum.FpUserRegistration'),
        ),
    ]
