# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 14:25


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fpraktikum', '0008_auto_20170802_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='FpInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='course name')),
                ('places', models.IntegerField(blank=True, null=True, verbose_name='places')),
                ('graduation',
                 models.CharField(blank=True, choices=[('BA', 'Bachelor'), ('MA', 'Master'), ('L', 'Lehramt')],
                                  max_length=2)),
                ('semester_half',
                 models.IntegerField(blank=True, choices=[(1, '1.'), (2, '2.'), (3, 'both')], null=True,
                                     verbose_name='semester half')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='institutes', to='fpraktikum.FpRegistration',
                                                   verbose_name='registration')),
            ],
            options={
                'verbose_name': 'institute',
                'verbose_name_plural': 'institutes',
            },
        ),
        migrations.CreateModel(
            name='FpUserPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='user name')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='user email')),
                ('user_snumber',
                 models.CharField(blank=True, max_length=100, null=True, verbose_name='s number / login')),
                ('institutes',
                 models.ManyToManyField(blank=True, to='fpraktikum.FpInstitute', verbose_name='institutes')),
            ],
            options={
                'verbose_name': 'User/Partner',
                'verbose_name_plural': 'Users/Partners',
            },
        ),
        migrations.CreateModel(
            name='FpUserRegistrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='user name')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='user email')),
                ('user_snumber',
                 models.CharField(blank=True, max_length=100, null=True, verbose_name='s number / login')),
                ('institutes',
                 models.ManyToManyField(blank=True, to='fpraktikum.FpInstitute', verbose_name='institutes')),
                ('partner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='registrant', to='fpraktikum.FpUserPartner',
                                                 verbose_name='partner')),
            ],
            options={
                'verbose_name': 'User/Registrant',
                'verbose_name_plural': 'Users/Registrants',
            },
        ),
        migrations.RemoveField(
            model_name='fpcoursefirsthalf',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='fpcoursesecondhalf',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='fpuserregistration',
            name='course_first_half',
        ),
        migrations.RemoveField(
            model_name='fpuserregistration',
            name='course_second_half',
        ),
        migrations.RemoveField(
            model_name='fpuserregistration',
            name='partner',
        ),
        migrations.AddField(
            model_name='fpwaitlist',
            name='user_snumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='s number / login'),
        ),
        migrations.DeleteModel(
            name='FpCourseFirstHalf',
        ),
        migrations.DeleteModel(
            name='FpCourseSecondHalf',
        ),
        migrations.DeleteModel(
            name='FpUserRegistration',
        ),
    ]
