# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fpraktikum', '0012_auto_20170912_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fpwaitlist',
            options={'verbose_name': 'Waitlist', 'verbose_name_plural': 'Waitlists'},
        ),
        migrations.RenameField(
            model_name='fpwaitlist',
            old_name='user_snumber',
            new_name='user_login',
        ),
        migrations.AddField(
            model_name='fpuserpartner',
            name='user_matrikel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Matrikelnumber'),
        ),
        migrations.AddField(
            model_name='fpuserregistrant',
            name='user_matrikel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Matrikelnumber'),
        ),
        migrations.AddField(
            model_name='fpwaitlist',
            name='user_firstname',
            field=models.CharField(max_length=100, null=True, verbose_name='user firstname'),
        ),
        migrations.AddField(
            model_name='fpwaitlist',
            name='user_lastname',
            field=models.CharField(max_length=100, null=True, verbose_name='user lastname'),
        ),
        migrations.AddField(
            model_name='fpwaitlist',
            name='user_matrikel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Matrikelnummer'),
        ),
        migrations.AlterUniqueTogether(
            name='fpuserpartner',
            unique_together=set([('user_firstname', 'user_lastname', 'user_email', 'user_login', 'user_matrikel')]),
        ),
        migrations.AlterUniqueTogether(
            name='fpuserregistrant',
            unique_together=set([('user_firstname', 'user_lastname', 'user_email', 'user_login', 'user_matrikel')]),
        ),
        migrations.RemoveField(
            model_name='fpwaitlist',
            name='user_name',
        ),
        migrations.AlterUniqueTogether(
            name='fpwaitlist',
            unique_together=set([('user_firstname', 'user_lastname', 'user_email', 'user_login', 'user_matrikel')]),
        ),
    ]
