# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fpraktikum', '0013_auto_20170913_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpuserpartner',
            name='has_accepted',
            field=models.BooleanField(default=False, verbose_name='Has accepted'),
        ),
    ]
