# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 10:46


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fpraktikum', '0015_auto_20170913_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fpinstitute',
            old_name='semester_half',
            new_name='semesterhalf',
        ),
    ]
