# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fpraktikum', '0016_auto_20170918_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fpuserpartner',
            old_name='user_email',
            new_name='user_mail',
        ),
        migrations.RenameField(
            model_name='fpuserregistrant',
            old_name='user_email',
            new_name='user_mail',
        ),
        migrations.RenameField(
            model_name='fpwaitlist',
            old_name='user_email',
            new_name='user_mail',
        ),
        migrations.AlterUniqueTogether(
            name='fpuserpartner',
            unique_together=set([('user_firstname', 'user_lastname', 'user_mail', 'user_login', 'user_matrikel')]),
        ),
        migrations.AlterUniqueTogether(
            name='fpuserregistrant',
            unique_together=set([('user_firstname', 'user_lastname', 'user_mail', 'user_login', 'user_matrikel')]),
        ),
        migrations.AlterUniqueTogether(
            name='fpwaitlist',
            unique_together=set([('user_firstname', 'user_lastname', 'user_mail', 'user_login', 'user_matrikel')]),
        ),
    ]
