# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fpraktikum', '0017_auto_20170918_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpwaitlist',
            name='graduation',
            field=models.CharField(blank=True, choices=[('BA', 'Bachelor'), ('MA', 'Master'), ('L', 'Lehramt')],
                                   max_length=2),
        ),
    ]
