# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpraktikum', '0018_fpwaitlist_graduation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpuserpartner',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='fpuserregistrant',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='fpwaitlist',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Notes'),
        ),
    ]
