# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpraktikum', '0019_auto_20170922_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpwaitlist',
            name='institute_firsthalf',
            field=models.CharField(blank=True, max_length=100, verbose_name='institute of first semesterhalf'),
        ),
        migrations.AddField(
            model_name='fpwaitlist',
            name='institute_secondhalf',
            field=models.CharField(blank=True, max_length=100, verbose_name='institute of second semesterhalf'),
        ),
        migrations.AlterField(
            model_name='fpregistration',
            name='semester',
            field=models.CharField(blank=True, default='SS18', max_length=4, verbose_name='semester'),
        ),
    ]
