# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpraktikum', '0020_auto_20180224_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpinstitute',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Notes'),
        ),
    ]
